### ISSUE TITLE
关于使用数学公式的问题

### ISSUE THREAD

**Issue by Heiku** [nameoverflow/hexo-theme-icalm#16]
你好，我在使用了这个主题后，发现数学公式总是渲染不出来，网上的方式都尝试了，看了以下你的博客是可以渲染出来的，想请教一下是怎么配置的？如果能有邮箱联系更好了

**Comment by nameoverflow** [comment]
这是hexo插件配置问题
https://github.com/nameoverflow/nameoverflow.github.io/blob/source/_config.yml#L75
