### ISSUE TITLE
Adding link to new page

### ISSUE THREAD

**Issue by lpzjerry** [nameoverflow/hexo-theme-icalm#5]
I typed command
```
hexo new page xxx
hexo g
```
under my root folder, and noticed that source/xxx/index.md and public/xxx/index.html are generated, without a link to the newly created page in the page bar. Under such case, I can access my new page only by typing in URL "http://my.page.url/xxx"...
I wonder whether there are some easier ways to add a new page than modifying the generated index.html?

**Comment by nameoverflow** [comment]
You can add an entry in [this file](https://github.com/nameoverflow/hexo-theme-icalm/blob/master/_config.yml#L5) to create a link in the bar
