### ISSUE TITLE
LaTex公式，集成MathJax出现的一些问题

### ISSUE THREAD

**Issue by qingdujun** [nameoverflow/hexo-theme-icalm#6]
但是存在一个问题就是，只有嵌入在行内的公式能被正确渲染。
单行公式存在如下问题，
- 点击Read More，或者标题进入之后，单行公式无法正确显示。$$ $$
- 此时如果刷新一下页面，单行公式就显示出来了？

演示地址：http://jqxx.xyz/
第一篇文章：“线性建模：最小二乘法”

**Comment by nameoverflow** [comment]
首先我自己是用 hexo 的 katex 插件做公式渲染的，没试过 mathjax。

然后 mathjax 依靠每次加载页面时调用脚本初始化来显示当前页面的公式，而我这个主题在点击 link 时不是直接加载新页面，而是取到目标页面的 body 做替换来获得更顺滑的效果。这样就会使一些依靠加载时初始化的脚本失效，需要写一些额外的代码，参考 [这里](https://github.com/nameoverflow/SinglePager#script-hook-tag)

当然我个人是更推荐 katex 的（逃

**Comment by nameoverflow** [comment]
你这个……我没能复现，点进去我看到的是正常的……

**Comment by nameoverflow** [comment]
这个主题在点击 link 的时候不是直接加载新页面，而是 ajax 拿到目标页的 body 进行替换。

于是像 mathjax 这种加载时初始化的东西就有点小问题，需要手动在代码里 hook ，参考[这里](https://github.com/nameoverflow/SinglePager#script-hook-tag)

这个问题可以先在[这前面](https://github.com/nameoverflow/hexo-theme-icalm/blob/master/layout/layout.ejs#L19)加一行代码

```HTML
<script>MathJax.Hub.Queue(["Typeset",MathJax.Hub]);</script>
```

使主题可以在每次进入新 link 时重置 mathjax（参考 mathjax 文档 http://docs.mathjax.org/en/latest/advanced/typeset.html#typeset-math）

我这并不是用的 instantClick 所以不能用 `InstantClick.on`，然后因为会把页面中所有的 `<script>` 替换掉，所以暂不能用 `<script type="math/tex; mode=display">`。

当然，我更推荐用 katex（233333

**Comment by nameoverflow** [comment]
我这并不是用的 instantClick 所以不能用 `InstantClick.on`

**Comment by qingdujun** [comment]
谢谢你的及时回答。是的，我原来将以下代码加在`content_view.ejs`里，可以正常显示`$$`行内公式，但是`$$$$`单行公式无法渲染。
``` javascript
<script language="JavaScript">
        MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
</script>
```
我尝试着将以上代码加在你说的位置`layout.ejs`，但问题并没有解决，和加在`content_view.ejs`效果一样。
``` javascript
<div data-pager-shell>
        <script>MathJax.Hub.Queue(["Typeset",MathJax.Hub]);</script>
        <%- body %>
        <%- partial('_partial/footer') %>
</div>
```
审查页面，也显示报错了。

- `InstantClick `这个其实没用到，我已经移除了。
- 另外，`<script type="math/tex; mode=display">`是单行公式的外标签。

或者`katex`如何集成进去呢？

**Comment by nameoverflow** [comment]
修复了 `math/tex` 丢失

```
git pull && git submodule update --remote
```

升级主题就可以了

**Comment by qingdujun** [comment]
现在，所有显示是正确的。
