### ISSUE TITLE
一个编号问题...

### ISSUE THREAD

**Issue by qingdujun** [nameoverflow/hexo-theme-icalm#7]
MathJax问题解决后。重复进入标签页，公式的编号会在原来的基础上累加，
- 1.2.3.4 (first)
- 5.6.7.8 (next)

演示地址：http://jqxx.xyz/
第一篇文章“线性建模：最小二乘法”。

**Comment by nameoverflow** [comment]
```
MathJax.Hub.Queue(["resetEquationNumbers", MathJax.InputJax.TeX]);
```

试试？

**Comment by qingdujun** [comment]
非常感谢！按照你说的，问题已经被解决。
