### ISSUE TITLE
<!--more-->无法识别可能是上面原因造成的呢？

### ISSUE THREAD

**Issue by qingdujun** [nameoverflow/hexo-theme-icalm#8]
<pre>
---
title: Hello World
---
Welcome to [Hexo](https://hexo.io/)! This is your very first post. Check [documentation](https://hexo.io/docs/) for more info. If you get any problems when using Hexo, you can find the answer in [troubleshooting](https://hexo.io/docs/troubleshooting.html) or you can ask me on [GitHub](https://github.com/hexojs/hexo/issues).

这里有个<@!--more-->

### Create a new post

``` bash
$ hexo new "My New Post"
```

</pre>

`@`符号是刚加上去的，防止HTML 给不显示了。

演示地址：http://www.qingdujun.com/

**Comment by nameoverflow** [comment]
演示地址没看出任何问题……
